# Generated by Django 5.0.3 on 2024-04-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_name_az_category_name_en_category_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
    ]
