# Generated by Django 5.0.3 on 2024-04-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_category_child_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='product.category'),
        ),
    ]
