# Generated by Django 5.0.3 on 2024-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_siblings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_to_wish_list',
            field=models.BooleanField(default=False),
        ),
    ]
