# Generated by Django 5.0.3 on 2024-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderitem_status'),
        ('product', '0010_product_siblings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='wish_list', to='product.product'),
        ),
    ]
