# Generated by Django 5.0.3 on 2024-03-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
